name: jsonplaceholder_client
description: A jsonplaceholder client for Dart.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.2.1+1
  fresh_dio:
    path: ../../../
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  very_good_analysis: ^5.0.0+1
