name: photos_repository
description: A Photos Dart Repository
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  jsonplaceholder_client:
    path: ../jsonplaceholder_client
  very_good_analysis: ^5.0.0+1
