name: fresh_dio
description: An http interceptor for token refresh. Fresh is built on top of package:dio and manages authentication tokens transparently.
repository: https://github.com/felangel/fresh
issue_tracker: https://github.com/felangel/fresh/issues
homepage: https://github.com/felangel/fresh

version: 0.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.2.1+1
  fresh: ^0.4.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
